# [target.aarch64-unknown-linux-gnu]
# pre-build = [
#   "dpkg --add-architecture $CROSS_DEB_ARCH",
#   "apt-get update",
#   "apt-get install --assume-yes nasm:$CROSS_DEB_ARCH",
# ]
[target.x86_64-unknown-linux-musl]
pre-build = [
  "dpkg --add-architecture $CROSS_DEB_ARCH",
  "apt-get update",
  "apt-get install --assume-yes nasm",
]
# [target.armv7-unknown-linux-musleabihf]
# pre-build = [
#   "dpkg --add-architecture $CROSS_DEB_ARCH",
#   "apt-get update",
#   "apt-get install --assume-yes nasm:$CROSS_DEB_ARCH",
# ]
