[book]
title = "Atomic Data Docs"
authors = ["Joep Meindertsma"]
description = "Documentation for the Atomic Data standard."
language = "en"

[output.html]
git-repository-icon = "fa-github"
git-repository-url = "https://github.com/atomicdata-dev/atomic-server"
edit-url-template = "https://github.com/atomicdata-dev/atomic-server/edit/develop/docs/{path}"
additional-css = ["atomic.css"]
additional-js = ["discord.js"]
fold.enable = true

[output.html.fold]
enable = true
level = 2

[output.linkcheck]
optional = true
